---
#
# Project:: Ansible Role - JumpCloud
#
# Copyright 2020, Route 1337, LLC, All Rights Reserved.
#
# Maintainers:
# - Matthew Ahrenstein: matthew@route1337.com
#
# See LICENSE
#

# Deploy and bind the JumpCloud Agent

- import_tasks: prereqs.yml
  when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'CentOS'
- import_tasks: jumpcloud.yml
  when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'CentOS'
