---
#
# Project:: Ansible Role - JumpCloud
#
# Copyright 2020, Route 1337 LLC, All Rights Reserved.
#
# Maintainers:
# - Matthew Ahrenstein: matthew@route1337.com
#
# See LICENSE
#

# Manage prerequisites for this role

- name: (Ubuntu) Update apt-cache
  apt:
    update_cache: yes
  when: ansible_distribution == 'Ubuntu'

- name: Verify curl is installed
  package:
    name: curl
    state: present

- name: Check if JumpCloud is already installed
  stat:
    path: /opt/jc
  register: jc_directory
